name: Quality checks 🧐

on:
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.5

      - name: Install dependencies
        run: |
          sudo gem install bundler
          bundle install

      - name: Run tests
        run: |
          bundle exec rspec

      - name: Run Rubocop
        run: |
          bundle exec rubocop
