name: Quality checks on PR 🧐

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Run tests
        run: |
          bundle exec rspec
      - name: Run Rubocop
        run: |
          bundle exec rubocop
