name: Quality checks 🧐

on:
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2

      - name: Install dependencies
        run: |
          sudo gem install bundler
          bundle install

      - name: Run Rubocop
        run: bundle exec rubocop

      - name: Run RSpec tests
        run: bundle exec rspec
