name: Quality checks 🧐

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12.1-alpine
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2

      - name: Install dependencies
        run: |
          sudo gem install bundler
          bundle install

      - name: Setup database
        env:
          RAILS_ENV: "test"
          DATABASE_URL: "postgres://postgres@localhost:5432/finance_flow_test"

      - name: See conection
        run: |
          rails c
          a = Entry.new({amount: 1})
          a.save!
          puts a
          
        run: |
          bundle exec rails db:setup
          bundle exec rspec

      - name: Run Rubocop
        run: |
          bundle exec rubocop
