name: Quality checks 🧐

on:
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12.1-alpine
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2

      - name: Setup database
        env:
          RAILS_ENV: "test"
          DATABASE_URL: "postgres://postgres@localhost:5432/finance_flow_test"
        run: |
          rails db:create
          rails db:migrate
          rails db:test:prepare

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2

      - name: Install dependencies
        run: |
          sudo gem install bundler
          bundle install

      - name: Run Rubocop
        run: |
          bundle exec rubocop

      - name: Run RSpec tests
        run: |
          bundle exec rspec
