name: Quality checks on PR 🧐

on:
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  rspec:
    name: Rubocop & RSpec
    runs-on: ubuntu-latest
    steps:
      - name: Run Rubocop
        run: |
          rubocop

      - name: Run Rspec
        run: |
          rspec
